# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresponse.proto\x12\x03\x64it\"\xa9\x01\n\x08Response\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12$\n\x0fresponse_status\x18\x04 \x01(\x0e\x32\x0b.dit.Status\x12\x12\n\nlatency_ms\x18\x05 \x01(\x03\x12\x1a\n\rerror_message\x18\x06 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_error_message*-\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUS']._serialized_start=195
  _globals['_STATUS']._serialized_end=240
  _globals['_RESPONSE']._serialized_start=24
  _globals['_RESPONSE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
